const AnomalyDetection = require('./anomalyDetection');
const InsightsService = require('./insightsService');
const RiskScoring = require('./riskScoring');
const AuditLog = require('../models/AuditLog');
const User = require('../models/User');

class AlertsService {
  /**
   * Generate intelligent alerts with severity levels
   * @param {Object} options - Alert generation options
   * @returns {Object} Alert report
   */
  static async generateIntelligentAlerts(options = {}) {
    try {
      const {
        timeRange = '24h',
        includeRecommendations = true,
        includeInsights = true,
        minSeverity = 'low',
        userId = null
      } = options;

      // Get anomaly report
      const anomalyReport = await AnomalyDetection.getAnomalyReport();
      
      // Filter anomalies by severity
      const filteredAnomalies = this.filterAnomaliesBySeverity(
        anomalyReport.anomalies,
        minSeverity
      );

      // Generate alerts from anomalies
      const alerts = await Promise.all(
        filteredAnomalies.map(anomaly => this.generateAlertFromAnomaly(anomaly, options))
      );

      // Add system alerts
      const systemAlerts = await this.generateSystemAlerts(options);
      
      // Add user-specific alerts if userId provided
      const userAlerts = userId ? await this.generateUserAlerts(userId, options) : [];

      const allAlerts = [...alerts, ...systemAlerts, ...userAlerts]
        .sort((a, b) => this.getSeverityScore(b.severity) - this.getSeverityScore(a.severity));

      const alertReport = {
        summary: this.generateAlertSummary(allAlerts),
        alerts: allAlerts,
        timeRange,
        generatedAt: new Date().toISOString(),
        nextCheck: this.calculateNextCheckTime()
      };

      return alertReport;
    } catch (error) {
      throw new Error(`Error generating intelligent alerts: ${error.message}`);
    }
  }

  /**
   * Generate alert from anomaly
   * @param {Object} anomaly - Anomaly object
   * @param {Object} options - Alert options
   * @returns {Object} Alert object
   */
  static async generateAlertFromAnomaly(anomaly, options) {
    const alert = {
      id: this.generateAlertId(),
      type: 'anomaly',
      subtype: anomaly.type,
      severity: anomaly.severity,
      title: this.generateAlertTitle(anomaly),
      description: anomaly.explanation,
      details: {
        anomaly: anomaly,
        riskScore: anomaly.riskScore,
        affectedResources: anomaly.evidenceIds || [anomaly.userId],
        metadata: anomaly.metadata
      },
      timestamp: anomaly.detectedAt,
      status: 'active',
      acknowledged: false,
      assignedTo: null,
      category: this.getAlertCategory(anomaly.type),
      priority: this.getAlertPriority(anomaly.severity),
      urgency: this.getAlertUrgency(anomaly.riskScore),
      impact: this.calculateAlertImpact(anomaly),
      recommendations: anomaly.recommendations,
      actions: this.generateAlertActions(anomaly),
      escalation: this.determineEscalation(anomaly),
      notifications: this.determineNotifications(anomaly),
      metadata: {
        source: 'anomaly_detection',
        autoGenerated: true,
        confidence: this.calculateAlertConfidence(anomaly)
      }
    };

    // Add insights if requested
    if (options.includeInsights) {
      alert.insights = await InsightsService.generateAnomalyInsights(anomaly);
    }

    return alert;
  }

  /**
   * Generate system alerts
   * @param {Object} options - Alert options
   * @returns {Array} System alerts
   */
  static async generateSystemAlerts(options) {
    const alerts = [];

    // Check system health
    const systemHealth = await this.checkSystemHealth();
    if (systemHealth.status !== 'healthy') {
      alerts.push({
        id: this.generateAlertId(),
        type: 'system',
        subtype: 'health',
        severity: systemHealth.severity,
        title: 'System Health Alert',
        description: `System health status: ${systemHealth.status}`,
        details: systemHealth,
        timestamp: new Date().toISOString(),
        status: 'active',
        acknowledged: false,
        category: 'system',
        priority: 'high',
        urgency: 'immediate',
        impact: 'system_wide',
        recommendations: systemHealth.recommendations,
        actions: [
          { type: 'monitor', label: 'Monitor System' },
          { type: 'restart', label: 'Restart Services' }
        ],
        escalation: { level: 'immediate', notifyAdmins: true },
        notifications: { email: true, sms: true, push: true },
        metadata: { source: 'system_monitor', autoGenerated: true }
      });
    }

    // Check storage capacity
    const storageStatus = await this.checkStorageCapacity();
    if (storageStatus.usage > 85) {
      alerts.push({
        id: this.generateAlertId(),
        type: 'system',
        subtype: 'storage',
        severity: storageStatus.usage > 95 ? 'critical' : 'high',
        title: 'Storage Capacity Alert',
        description: `Storage usage at ${storageStatus.usage}%`,
        details: storageStatus,
        timestamp: new Date().toISOString(),
        status: 'active',
        acknowledged: false,
        category: 'system',
        priority: 'medium',
        urgency: 'normal',
        impact: 'performance',
        recommendations: ['Clean up old files', 'Archive old evidence', 'Expand storage'],
        actions: [
          { type: 'cleanup', label: 'Start Cleanup' },
          { type: 'archive', label: 'Archive Files' }
        ],
        escalation: { level: 'normal', notifyAdmins: false },
        notifications: { email: true, sms: false, push: true },
        metadata: { source: 'storage_monitor', autoGenerated: true }
      });
    }

    // Check database performance
    const dbPerformance = await this.checkDatabasePerformance();
    if (dbPerformance.slowQueries > 10) {
      alerts.push({
        id: this.generateAlertId(),
        type: 'system',
        subtype: 'database',
        severity: 'medium',
        title: 'Database Performance Alert',
        description: `${dbPerformance.slowQueries} slow queries detected`,
        details: dbPerformance,
        timestamp: new Date().toISOString(),
        status: 'active',
        acknowledged: false,
        category: 'performance',
        priority: 'medium',
        urgency: 'normal',
        impact: 'performance',
        recommendations: ['Optimize queries', 'Add indexes', 'Review database load'],
        actions: [
          { type: 'optimize', label: 'Optimize Database' },
          { type: 'analyze', label: 'Analyze Queries' }
        ],
        escalation: { level: 'normal', notifyAdmins: false },
        notifications: { email: true, sms: false, push: false },
        metadata: { source: 'database_monitor', autoGenerated: true }
      });
    }

    return alerts;
  }

  /**
   * Generate user-specific alerts
   * @param {number} userId - User ID
   * @param {Object} options - Alert options
   * @returns {Array} User alerts
   */
  static async generateUserAlerts(userId, options) {
    const alerts = [];

    // Check user activity patterns
    const userActivity = await this.analyzeUserActivity(userId);
    if (userActivity.anomalous) {
      alerts.push({
        id: this.generateAlertId(),
        type: 'user',
        subtype: 'activity_pattern',
        severity: userActivity.severity,
        title: 'User Activity Alert',
        description: `Unusual activity pattern detected for user ${userId}`,
        details: userActivity,
        timestamp: new Date().toISOString(),
        status: 'active',
        acknowledged: false,
        category: 'user_behavior',
        priority: 'medium',
        urgency: 'normal',
        impact: 'security',
        recommendations: userActivity.recommendations,
        actions: [
          { type: 'review', label: 'Review Activity' },
          { type: 'contact', label: 'Contact User' }
        ],
        escalation: { level: 'normal', notifyAdmins: false },
        notifications: { email: true, sms: false, push: true },
        metadata: { source: 'user_monitor', autoGenerated: true, userId }
      });
    }

    // Check user access patterns
    const userAccess = await this.analyzeUserAccess(userId);
    if (userAccess.suspicious) {
      alerts.push({
        id: this.generateAlertId(),
        type: 'user',
        subtype: 'access_pattern',
        severity: 'high',
        title: 'User Access Alert',
        description: `Suspicious access pattern detected for user ${userId}`,
        details: userAccess,
        timestamp: new Date().toISOString(),
        status: 'active',
        acknowledged: false,
        category: 'security',
        priority: 'high',
        urgency: 'immediate',
        impact: 'security',
        recommendations: userAccess.recommendations,
        actions: [
          { type: 'investigate', label: 'Investigate Access' },
          { type: 'restrict', label: 'Restrict Access' }
        ],
        escalation: { level: 'immediate', notifyAdmins: true },
        notifications: { email: true, sms: true, push: true },
        metadata: { source: 'access_monitor', autoGenerated: true, userId }
      });
    }

    return alerts;
  }

  /**
   * Get active alerts
   * @param {Object} filters - Alert filters
   * @returns {Array} Active alerts
   */
  static async getActiveAlerts(filters = {}) {
    try {
      const {
        severity = null,
        category = null,
        userId = null,
        status = 'active',
        limit = 100
      } = filters;

      // Generate current alerts
      const alertReport = await this.generateIntelligentAlerts({
        minSeverity: severity || 'low',
        userId
      });

      let alerts = alertReport.alerts;

      // Apply filters
      if (category) {
        alerts = alerts.filter(alert => alert.category === category);
      }

      if (status) {
        alerts = alerts.filter(alert => alert.status === status);
      }

      return alerts.slice(0, limit);
    } catch (error) {
      throw new Error(`Error getting active alerts: ${error.message}`);
    }
  }

  /**
   * Acknowledge alert
   * @param {string} alertId - Alert ID
   * @param {number} userId - User ID acknowledging
   * @param {string} notes - Acknowledgment notes
   * @returns {Object} Acknowledgment result
   */
  static async acknowledgeAlert(alertId, userId, notes = '') {
    try {
      // In a real implementation, this would update a database
      // For now, return a simulated response
      
      return {
        success: true,
        alertId,
        acknowledgedBy: userId,
        acknowledgedAt: new Date().toISOString(),
        notes,
        status: 'acknowledged'
      };
    } catch (error) {
      throw new Error(`Error acknowledging alert: ${error.message}`);
    }
  }

  /**
   * Resolve alert
   * @param {string} alertId - Alert ID
   * @param {number} userId - User ID resolving
   * @param {string} resolution - Resolution notes
   * @returns {Object} Resolution result
   */
  static async resolveAlert(alertId, userId, resolution = '') {
    try {
      // In a real implementation, this would update a database
      // For now, return a simulated response
      
      return {
        success: true,
        alertId,
        resolvedBy: userId,
        resolvedAt: new Date().toISOString(),
        resolution,
        status: 'resolved'
      };
    } catch (error) {
      throw new Error(`Error resolving alert: ${error.message}`);
    }
  }

  /**
   * Get alert statistics
   * @param {Object} filters - Statistics filters
   * @returns {Object} Alert statistics
   */
  static async getAlertStatistics(filters = {}) {
    try {
      const alertReport = await this.generateIntelligentAlerts(filters);
      const alerts = alertReport.alerts;

      const statistics = {
        total: alerts.length,
        bySeverity: this.groupAlertsByField(alerts, 'severity'),
        byCategory: this.groupAlertsByField(alerts, 'category'),
        byType: this.groupAlertsByField(alerts, 'type'),
        byStatus: this.groupAlertsByField(alerts, 'status'),
        averageRiskScore: alerts.length > 0 
          ? (alerts.reduce((sum, alert) => sum + (alert.details.riskScore || 0), 0) / alerts.length).toFixed(1)
          : 0,
        trends: await this.calculateAlertTrends(),
        topUsers: await this.getTopUsersByAlerts(alerts),
        resolutionTime: this.calculateAverageResolutionTime(alerts)
      };

      return statistics;
    } catch (error) {
      throw new Error(`Error getting alert statistics: ${error.message}`);
    }
  }

  /**
   * Helper methods
   */
  static generateAlertId() {
    return `alert_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  static filterAnomaliesBySeverity(anomalies, minSeverity) {
    const severityLevels = { low: 1, medium: 2, high: 3, critical: 4 };
    const minLevel = severityLevels[minSeverity] || 1;
    
    return anomalies.filter(anomaly => 
      severityLevels[anomaly.severity] >= minLevel
    );
  }

  static generateAlertTitle(anomaly) {
    const titles = {
      'duplicate_evidence': 'Duplicate Evidence Detected',
      'cross_case_usage': 'Cross-Case Evidence Usage Alert',
      'bulk_upload_pattern': 'Bulk Upload Pattern Alert',
      'rapid_upload_pattern': 'Rapid Upload Pattern Alert'
    };
    
    return titles[anomaly.type] || 'Anomaly Detected';
  }

  static getAlertCategory(type) {
    const categories = {
      'duplicate_evidence': 'data_integrity',
      'cross_case_usage': 'evidence_management',
      'bulk_upload_pattern': 'user_behavior',
      'rapid_upload_pattern': 'user_behavior'
    };
    
    return categories[type] || 'other';
  }

  static getAlertPriority(severity) {
    const priorities = {
      'critical': 'P0',
      'high': 'P1',
      'medium': 'P2',
      'low': 'P3'
    };
    
    return priorities[severity] || 'P4';
  }

  static getAlertUrgency(riskScore) {
    if (riskScore >= 80) return 'immediate';
    if (riskScore >= 60) return 'urgent';
    if (riskScore >= 40) return 'normal';
    return 'low';
  }

  static calculateAlertImpact(anomaly) {
    const impacts = {
      'duplicate_evidence': 'data_integrity',
      'cross_case_usage': 'evidence_contamination',
      'bulk_upload_pattern': 'system_load',
      'rapid_upload_pattern': 'security_risk'
    };
    
    return impacts[anomaly.type] || 'unknown';
  }

  static generateAlertActions(anomaly) {
    const actions = {
      'duplicate_evidence': [
        { type: 'investigate', label: 'Investigate Duplicates' },
        { type: 'review', label: 'Review Evidence' },
        { type: 'merge', label: 'Merge Duplicates' }
      ],
      'cross_case_usage': [
        { type: 'investigate', label: 'Investigate Cross-Usage' },
        { type: 'review', label: 'Review Cases' },
        { type: 'document', label: 'Document Usage' }
      ],
      'bulk_upload_pattern': [
        { type: 'review', label: 'Review Uploads' },
        { type: 'contact', label: 'Contact User' },
        { type: 'monitor', label: 'Monitor Activity' }
      ],
      'rapid_upload_pattern': [
        { type: 'investigate', label: 'Investigate Pattern' },
        { type: 'verify', label: 'Verify Authorization' },
        { type: 'restrict', label: 'Restrict Access' }
      ]
    };
    
    return actions[anomaly.type] || [
      { type: 'review', label: 'Review Alert' },
      { type: 'investigate', label: 'Investigate Issue' }
    ];
  }

  static determineEscalation(anomaly) {
    if (anomaly.severity === 'critical') {
      return { level: 'immediate', notifyAdmins: true, notifyManagers: true };
    } else if (anomaly.severity === 'high') {
      return { level: 'urgent', notifyAdmins: false, notifyManagers: true };
    } else {
      return { level: 'normal', notifyAdmins: false, notifyManagers: false };
    }
  }

  static determineNotifications(anomaly) {
    const notifications = {
      'critical': { email: true, sms: true, push: true, inApp: true },
      'high': { email: true, sms: false, push: true, inApp: true },
      'medium': { email: true, sms: false, push: false, inApp: true },
      'low': { email: false, sms: false, push: false, inApp: true }
    };
    
    return notifications[anomaly.severity] || notifications.low;
  }

  static calculateAlertConfidence(anomaly) {
    let confidence = 0.8; // Base confidence
    
    // Increase confidence based on multiple factors
    if (anomaly.duplicateCount > 5) confidence += 0.1;
    if (anomaly.affectedCases > 3) confidence += 0.05;
    if (anomaly.riskScore > 70) confidence += 0.05;
    
    return Math.min(1.0, confidence);
  }

  static getSeverityScore(severity) {
    const scores = {
      'critical': 4,
      'high': 3,
      'medium': 2,
      'low': 1
    };
    
    return scores[severity] || 0;
  }

  static generateAlertSummary(alerts) {
    const summary = {
      total: alerts.length,
      critical: alerts.filter(a => a.severity === 'critical').length,
      high: alerts.filter(a => a.severity === 'high').length,
      medium: alerts.filter(a => a.severity === 'medium').length,
      low: alerts.filter(a => a.severity === 'low').length,
      byCategory: this.groupAlertsByField(alerts, 'category'),
      byType: this.groupAlertsByField(alerts, 'type'),
      acknowledged: alerts.filter(a => a.acknowledged).length,
      pending: alerts.filter(a => !a.acknowledged).length
    };
    
    return summary;
  }

  static groupAlertsByField(alerts, field) {
    return alerts.reduce((groups, alert) => {
      const value = alert[field] || 'unknown';
      groups[value] = (groups[value] || 0) + 1;
      return groups;
    }, {});
  }

  static calculateNextCheckTime() {
    const nextCheck = new Date();
    nextCheck.setMinutes(nextCheck.getMinutes() + 30); // Check every 30 minutes
    return nextCheck.toISOString();
  }

  // Placeholder methods for system checks
  static async checkSystemHealth() {
    return {
      status: 'healthy',
      severity: 'low',
      recommendations: []
    };
  }

  static async checkStorageCapacity() {
    return {
      usage: 75,
      available: '25GB',
      total: '100GB',
      recommendations: []
    };
  }

  static async checkDatabasePerformance() {
    return {
      slowQueries: 3,
      avgQueryTime: '45ms',
      recommendations: []
    };
  }

  static async analyzeUserActivity(userId) {
    return {
      anomalous: false,
      severity: 'low',
      recommendations: []
    };
  }

  static async analyzeUserAccess(userId) {
    return {
      suspicious: false,
      recommendations: []
    };
  }

  static async calculateAlertTrends() {
    return {
      daily: [],
      weekly: [],
      monthly: []
    };
  }

  static async getTopUsersByAlerts(alerts) {
    return [];
  }

  static calculateAverageResolutionTime(alerts) {
    return '2.5 hours';
  }
}

module.exports = AlertsService;
